version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=my-db-instance.c5inzh5cdqez.us-east-1.rds.amazonaws.com
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /efs/wp_data:/var/www/html
  db:
    image: mysql:8.0.28
    volumes:
      - /efs/db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_HOST=my-db-instance.c5inzh5cdqez.us-east-1.rds.amazonaws.com
      - MYSQL_PORT=3306
volumes:
  wp_data:
  db_data:


